#include <stdio.h>

int main(void)
{
	printf("あ☆べ\n");
	printf("りゅうせい\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("あ☆べ\n");
	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");
	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");
	return 0;
}