#include <stdio.h>

int main(void)
{
	printf("話をしよう。\n");
	printf("あれは今から、３６万...\nいや、１万２０００年前の出来事。\n");
	printf("私にとっては昨日の出来事のようだが.../n君たちにとっては/n/n明日の出来事だ。\n");
	printf("あ☆べ\n");
	printf("りゅうせい\n");
	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");
	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");	printf("アップルワッシャー\n");
	printf("ぬまたようへい\n");
	return 0;
}